### PR TITLE
Openaddresses importing

### LINKED ISSUE #12: Openaddresses can't be imported on vagrant box
Our vagrant setup doesn't support importing openaddresses, we just have to bring the configuration over.

### PR DESCRIPTION
**Pull request by orangejulius**
Allows importing individual files or the whole thing

Fixes #12

### CODE REVIEW

**Comment by orangejulius** [comment]
hey @heffergm, if you get a chance can you look over these changes? I'm not a chef expert, would love to hear any suggestions for improvements

**Comment by heffergm** [comment]
A few changes here: https://github.com/pelias/vagrant/pull/14

**Comment by orangejulius** [comment]
Updated with some bugfixes and grant's improvements from #14

**Comment by orangejulius** [comment]
merged on the cli

**Pull request closed without merging**
